<template>
    <Head :title="`Weather: ${port.name}`" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="text-xl font-semibold leading-tight text-gray-800">
                Weather & Risk Analysis for {{ port.name }}
            </h2>
        </template>

        <div class="py-12">
            <div class="mx-auto max-w-7xl sm:px-6 lg:px-8 space-y-6">
                
                <div class="mb-4">
                     <a :href="route('schedules.index')" class="text-blue-500 hover:underline">← Back to Schedules</a>
                </div>

                <div v-if="weather" class="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <!-- Weather Details -->
                    <div class="bg-white p-6 rounded-xl shadow-lg border">
                        <h2 class="text-xl font-semibold mb-4 text-gray-700">Current Conditions</h2>
                        <div class="space-y-4">
                            <div class="flex justify-between border-b pb-2">
                                <span class="text-gray-500">Wind Speed</span>
                                <span class="font-bold">{{ weather.wind_speed }} km/h</span>
                            </div>
                            <div class="flex justify-between border-b pb-2">
                                <span class="text-gray-500">Wave Height</span>
                                <span class="font-bold">{{ weather.wave_height }} m</span>
                            </div>
                            <div class="flex justify-between border-b pb-2">
                                <span class="text-gray-500">Visibility</span>
                                <span class="font-bold">{{ weather.visibility || 'N/A' }} km</span>
                            </div>
                            <div class="flex justify-between border-b pb-2">
                                <span class="text-gray-500">Precipitation</span>
                                <span class="font-bold">{{ weather.precipitation || '0' }} mm</span>
                            </div>
                            <div class="text-sm text-gray-400 mt-4 text-right">
                                Recorded: {{ new Date(weather.recorded_at).toLocaleString() }}
                            </div>
                        </div>
                    </div>

                    <!-- Risk Analysis (AI Prediction) -->
                    <div class="bg-white p-6 rounded-xl shadow-lg border flex flex-col items-center justify-center text-center">
                        <h2 class="text-xl font-semibold mb-2 text-gray-700">Cancellation Risk</h2>
                        
                        <div 
                            class="w-40 h-40 rounded-full flex flex-col items-center justify-center border-8 text-3xl font-bold shadow-inner my-4"
                            :class="{
                                'border-green-500 text-green-600': risk_analysis.color === 'green',
                                'border-yellow-500 text-yellow-600': risk_analysis.color === 'yellow',
                                'border-red-500 text-red-600': risk_analysis.color === 'red',
                                'border-gray-300': risk_analysis.color === 'gray'
                            }"
                        >
                            {{ weather.risk_score }}%
                            <span class="text-xs font-normal block text-gray-400 mt-1">Probability</span>
                        </div>
                        
                        <div 
                            class="text-2xl font-bold px-6 py-2 rounded-lg"
                            :class="{
                                'bg-green-100 text-green-800': risk_analysis.color === 'green',
                                'bg-yellow-100 text-yellow-800': risk_analysis.color === 'yellow',
                                'bg-red-100 text-red-800': risk_analysis.color === 'red',
                            }"
                        >
                            {{ risk_analysis.status }}
                        </div>
                        <p class="text-gray-500 mt-4 px-4 text-sm">
                            This prediction is generated by our AI model based on current sea and wind conditions.
                        </p>
                    </div>
                </div>

                <div v-else class="text-center p-10 bg-white rounded shadow">
                    <p class="text-xl text-gray-500">No weather data available for this port yet.</p>
                </div>

                <!-- Manual Update Form (For Demo/Admin) -->
                <div class="bg-gray-100 p-6 rounded border">
                    <div class="flex justify-between items-center mb-4">
                        <h3 class="font-bold text-gray-700">Simulate or Fetch Weather Data</h3>
                        <button @click="refreshWeather" type="button" class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded shadow text-sm flex items-center gap-2">
                             <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                            </svg>
                            Fetch Live Data (Windy/OpenMeteo)
                        </button>
                    </div>
                    <form @submit.prevent="submit" class="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div>
                            <input v-model="form.wind_speed" type="number" step="0.1" placeholder="Wind (km/h)" class="w-full p-2 rounded border" :class="{'border-red-500': form.errors.wind_speed}">
                            <div v-if="form.errors.wind_speed" class="text-red-500 text-xs mt-1">{{ form.errors.wind_speed }}</div>
                        </div>
                        <div>
                            <input v-model="form.wave_height" type="number" step="0.1" placeholder="Wave (m)" class="w-full p-2 rounded border" :class="{'border-red-500': form.errors.wave_height}">
                            <div v-if="form.errors.wave_height" class="text-red-500 text-xs mt-1">{{ form.errors.wave_height }}</div>
                        </div>
                        <div>
                            <input v-model="form.visibility" type="number" step="0.1" placeholder="Visibility (km)" class="w-full p-2 rounded border" :class="{'border-red-500': form.errors.visibility}">
                             <div v-if="form.errors.visibility" class="text-red-500 text-xs mt-1">{{ form.errors.visibility }}</div>
                        </div>
                        <div>
                            <input v-model="form.precipitation" type="number" step="0.1" placeholder="Rain (mm)" class="w-full p-2 rounded border" :class="{'border-red-500': form.errors.precipitation}">
                             <div v-if="form.errors.precipitation" class="text-red-500 text-xs mt-1">{{ form.errors.precipitation }}</div>
                        </div>
                        <button type="submit" class="bg-indigo-600 text-white p-2 rounded col-span-2 md:col-span-4 hover:bg-indigo-700">Update Weather & Recalculate Risk</button>
                    </form>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm } from '@inertiajs/vue3';

const props = defineProps({
    port: Object,
    weather: Object,
    risk_analysis: Object
});

const form = useForm({
    wind_speed: '',
    wave_height: '',
    visibility: '',
    precipitation: ''
});

const submit = () => {
    form.post(route('weather.store', props.port.id), {
        onSuccess: () => form.reset(),
        preserveScroll: true
    });
};

const refreshWeather = () => {
    if (confirm('Fetch real-time weather data for this location?')) {
        form.post(route('weather.refresh', props.port.id), {
            preserveScroll: true
        });
    }
};
</script>
